image:
  fluent_bit:
    repository: fluent/fluent-bit
    tag: 1.2.2

backend:
  type: es
  es:
    host: elasticsearch-client.logging.svc.cluster.local
    time_key: "@timestamp_fb"
    port: 9200

parsers:
  enabled: true
  regex:
  - name: loadtester
    regex: '^(?<time>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3})\s(?<action>[^\s]+)\s(?<status>[A-Z]+)\s?(?<duration>[0-9\.]*)\s?(?<message>.*)$'
    timeKey: time
    timeFormat: "%Y-%d-%m %H:%M:%S.%f"

extraEntries:
  filter: |-
    [FILTER]
      Name    modify
      Match   mem.*
