apiVersion: v1
kind: ConfigMap
metadata:
  name: load-test-config
data:
  test.yaml: |    # Adjust config
    gerrit:
      url: http://localhost:8080
    testrun:
      duration: null
      initialization:
        createProjects:
          enabled: true
          number: 1
        knownProjects: []
      waitBetweenCycles:
        enabled: true
        min: 1
        max: 10

    actions:
      clone_project:
        probability: 1
      create_project:
        probability: 1
      fetch_project:
        probability: 1
      push_for_review:
        probability: 1
      push_head_to_master:
        probability: 1
      query_changes:
        probability: 1
      query_projects:
        probability: 1
      review_change:
        probability: 1
